const canvas = document.querySelector('#battlefield');
const ctx = canvas.getContext('2d');
const toast = document.querySelector('#toast');
const units = [
  { id: 1, name: '蓝军步兵师-01', type: 'infantry', side: 'blue', x: 240, y: 450, hp: 100, morale: 86, radius: 12, speed: 82, route: [], routeIndex: 0, selected: false },
  { id: 2, name: '蓝军装甲师-01', type: 'armor', side: 'blue', x: 295, y: 480, hp: 100, morale: 72, radius: 15, speed: 52, route: [], routeIndex: 0, selected: false },
  { id: 3, name: '蓝军步兵师-02', type: 'infantry', side: 'blue', x: 205, y: 505, hp: 100, morale: 94, radius: 11, speed: 96, route: [], routeIndex: 0, selected: false }
];
const enemies = [
  { id: 101, name: '红军步兵师-01', type: 'infantry', side: 'red', x: 735, y: 175, hp: 100, morale: 80, radius: 13, speed: 0 },
  { id: 102, name: '红军装甲师-01', type: 'armor', side: 'red', x: 790, y: 215, hp: 100, morale: 65, radius: 16, speed: 0 },
  { id: 103, name: '红军步兵师-02', type: 'infantry', side: 'red', x: 682, y: 235, hp: 100, morale: 88, radius: 11, speed: 0 },
  { id: 104, name: '红军装甲师-02', type: 'armor', side: 'red', x: 630, y: 145, hp: 100, morale: 77, radius: 12, speed: 0 }
];
let dragging = false, dragStart = null, dragEnd = null, routeDrawing = false, currentRoute = [], paused = false, seconds = 272, combatNoticeAt = 0, lastFrame = performance.now();
function showToast(message) { toast.textContent = message; toast.classList.add('show'); clearTimeout(showToast.timer); showToast.timer = setTimeout(() => toast.classList.remove('show'), 2200); }
function allUnits() { return units.concat(enemies); }
function selectedUnits() { return units.filter(unit => unit.selected); }
function updateList() { document.querySelector('#unitList').innerHTML = units.map(unit => `<div class="unit-card ${unit.selected ? 'active' : ''}" data-id="${unit.id}"><span class="unit-avatar blue-avatar">●</span><span><b>${unit.name}</b><small>${unit.type === 'armor' ? '装甲师' : '步兵师'} · 血量 ${Math.round(unit.hp)} · 士气 ${Math.round(unit.morale)}</small></span><span class="unit-hp"><i style="width:${unit.hp}%"></i></span></div>`).join(''); document.querySelector('#unitCount').textContent = `${units.length.toString().padStart(2, '0')} UNITS`; document.querySelectorAll('.unit-card').forEach(card => card.addEventListener('click', () => { units.forEach(unit => unit.selected = unit.id === Number(card.dataset.id)); updateList(); updateReadout(); })); }
function updateReadout() { const selected = selectedUnits(); document.querySelector('#selectionReadout').textContent = selected.length ? `${selected.length} BLUE UNIT${selected.length > 1 ? 'S' : ''} SELECTED` : '未选择单位'; }
function drawTerrain() { ctx.fillStyle = '#a7c942'; ctx.fillRect(0, 0, canvas.width, canvas.height); ctx.fillStyle = '#536426'; ctx.beginPath(); ctx.moveTo(0, 0); ctx.lineTo(280, 0); ctx.lineTo(350, 120); ctx.lineTo(300, 270); ctx.lineTo(0, 300); ctx.closePath(); ctx.fill(); ctx.fillStyle = '#2798ed'; ctx.beginPath(); ctx.moveTo(475, -20); ctx.bezierCurveTo(560, 85, 390, 155, 535, 235); ctx.bezierCurveTo(690, 320, 780, 135, 960, 180); ctx.lineTo(960, 285); ctx.bezierCurveTo(760, 230, 700, 420, 520, 305); ctx.bezierCurveTo(340, 195, 520, 100, 420, -20); ctx.closePath(); ctx.fill(); ctx.fillStyle = '#4b4b53'; [[120, 205, 100, 48], [265, 355, 140, 73], [860, 355, 105, 46], [630, 80, 75, 48]].forEach(([x, y, rx, ry]) => { ctx.beginPath(); ctx.ellipse(x, y, rx, ry, -.25, 0, Math.PI * 2); ctx.fill(); }); ctx.strokeStyle = '#779a3b'; ctx.lineWidth = 2; for (let x = 0; x < canvas.width; x += 48) { ctx.beginPath(); ctx.moveTo(x, 0); ctx.lineTo(x, canvas.height); ctx.stroke(); } for (let y = 0; y < canvas.height; y += 48) { ctx.beginPath(); ctx.moveTo(0, y); ctx.lineTo(canvas.width, y); ctx.stroke(); } }
function drawFlag(x, y, side) { ctx.strokeStyle = '#252c2e'; ctx.lineWidth = 2; ctx.beginPath(); ctx.moveTo(x, y); ctx.lineTo(x, y - 30); ctx.stroke(); ctx.fillStyle = side === 'red' ? '#e93227' : '#1911ce'; ctx.beginPath(); ctx.moveTo(x, y - 30); ctx.lineTo(x + 20, y - 24); ctx.lineTo(x, y - 18); ctx.closePath(); ctx.fill(); ctx.fillStyle = '#f2d51a'; ctx.beginPath(); ctx.arc(x, y + 2, 6, 0, Math.PI * 2); ctx.fill(); }
function drawBases() { drawFlag(116, 170, 'blue'); drawFlag(844, 456, 'red'); ctx.fillStyle = '#f5dc1c'; ctx.font = 'bold 12px IBM Plex Mono'; ctx.fillText('BLUE HQ', 83, 190); ctx.fillText('RED HQ', 820, 476); }
function drawResource() { ctx.fillStyle = '#f4d71a'; ctx.beginPath(); ctx.arc(480, 365, 12, 0, Math.PI * 2); ctx.fill(); ctx.fillStyle = '#554b1d'; ctx.font = 'bold 11px IBM Plex Mono'; ctx.fillText('RESOURCE', 444, 390); }
function getControlLineSamples() { const livingBlue = units.filter(unit => unit.hp > 0); const livingRed = enemies.filter(unit => unit.hp > 0); const blueAverage = livingBlue.reduce((sum, unit) => sum + unit.x, 0) / Math.max(1, livingBlue.length); const redAverage = livingRed.reduce((sum, unit) => sum + unit.x, 0) / Math.max(1, livingRed.length); return Array.from({ length: 17 }, (_, index) => { const y = index * canvas.height / 16; const blueAtDepth = livingBlue.filter(unit => Math.abs(unit.y - y) < 155); const redAtDepth = livingRed.filter(unit => Math.abs(unit.y - y) < 155); const blueX = blueAtDepth.length ? blueAtDepth.reduce((sum, unit) => sum + unit.x, 0) / blueAtDepth.length : blueAverage; const redX = redAtDepth.length ? redAtDepth.reduce((sum, unit) => sum + unit.x, 0) / redAtDepth.length : redAverage; return { x: (blueX + redX) / 2, y }; }); }
function drawFog() { const samples = getControlLineSamples(); ctx.save(); ctx.fillStyle = 'rgba(12, 20, 22, .63)'; ctx.beginPath(); ctx.moveTo(samples[0].x + 70, 0); samples.forEach((sample, index) => { const previous = samples[Math.max(0, index - 1)]; const next = samples[Math.min(samples.length - 1, index + 1)]; const boundary = Math.max(0, sample.x + 70 - Math.abs(next.x - previous.x) * .25); if (index === 0) ctx.lineTo(boundary, sample.y); else { const midpoint = (previous.y + sample.y) / 2; ctx.bezierCurveTo(previous.x + 70, midpoint, boundary, midpoint, boundary, sample.y); } }); ctx.lineTo(canvas.width, canvas.height); ctx.lineTo(canvas.width, 0); ctx.closePath(); ctx.fill(); ctx.restore(); }
function drawControlLine() { const samples = getControlLineSamples(); ctx.save(); ctx.strokeStyle = 'rgba(16, 20, 20, .82)'; ctx.lineWidth = 4; ctx.beginPath(); ctx.moveTo(samples[0].x, samples[0].y); for (let index = 1; index < samples.length; index += 1) { const previous = samples[index - 1]; const current = samples[index]; const midpoint = (previous.y + current.y) / 2; ctx.bezierCurveTo(previous.x, midpoint, current.x, midpoint, current.x, current.y); } ctx.stroke(); ctx.fillStyle = '#111'; ctx.font = '600 11px IBM Plex Mono'; ctx.fillText('ACTUAL CONTROL LINE', samples[0].x + 12, 28); ctx.restore(); }
function drawArrow(from, to) { const angle = Math.atan2(to.y - from.y, to.x - from.x); ctx.beginPath(); ctx.moveTo(to.x, to.y); ctx.lineTo(to.x - 13 * Math.cos(angle - Math.PI / 6), to.y - 13 * Math.sin(angle - Math.PI / 6)); ctx.moveTo(to.x, to.y); ctx.lineTo(to.x - 13 * Math.cos(angle + Math.PI / 6), to.y - 13 * Math.sin(angle + Math.PI / 6)); ctx.stroke(); }
function drawRoutes() { units.forEach(unit => { if (!unit.route.length) return; ctx.save(); ctx.strokeStyle = 'rgba(70, 70, 70, .58)'; ctx.lineWidth = 4; ctx.beginPath(); ctx.moveTo(unit.x, unit.y); unit.route.slice(unit.routeIndex).forEach(point => ctx.lineTo(point.x, point.y)); ctx.stroke(); const remaining = unit.route.slice(unit.routeIndex); const target = unit.route[unit.route.length - 1]; const previous = remaining.length > 1 ? remaining[remaining.length - 2] : unit; ctx.fillStyle = 'rgba(70, 70, 70, .72)'; ctx.beginPath(); ctx.arc(target.x, target.y, 4, 0, Math.PI * 2); ctx.fill(); drawArrow(previous, target); ctx.restore(); }); if (routeDrawing && currentRoute.length > 1) { ctx.save(); ctx.strokeStyle = 'rgba(70, 70, 70, .62)'; ctx.lineWidth = 4; ctx.beginPath(); ctx.moveTo(currentRoute[0].x, currentRoute[0].y); currentRoute.slice(1).forEach(point => ctx.lineTo(point.x, point.y)); ctx.stroke(); drawArrow(currentRoute[currentRoute.length - 2], currentRoute[currentRoute.length - 1]); ctx.restore(); } }
function findContact(unit) { return allUnits().find(other => other.side !== unit.side && other.hp > 0 && Math.hypot(unit.x - other.x, unit.y - other.y) <= unit.radius + other.radius + 2); }
function updateCombat(unit, delta) { const opponent = findContact(unit); if (!opponent) { unit.disengaging = false; return false; } if (unit.disengaging) return false; unit.tx = unit.x; unit.ty = unit.y; opponent.tx = opponent.x; opponent.ty = opponent.y; unit.hp = Math.max(0, unit.hp - delta * .9); opponent.hp = Math.max(0, opponent.hp - delta * .9); unit.morale = Math.max(0, unit.morale - delta * 2.1); opponent.morale = Math.max(0, opponent.morale - delta * 2.1); if (Date.now() - combatNoticeAt > 2800) { showToast('红蓝军接触，战斗开始！血量与士气正在下降。'); combatNoticeAt = Date.now(); } return true; }
function recoverUnit(unit, delta) { const nearestEnemy = enemies.reduce((nearest, enemy) => Math.min(nearest, Math.hypot(unit.x - enemy.x, unit.y - enemy.y)), Infinity); if (!findContact(unit)) unit.morale = Math.min(100, unit.morale + delta * 3.8); if (nearestEnemy > 150) unit.hp = Math.min(100, unit.hp + delta * 2.6); }
function moveUnit(unit, delta) { if (unit.side !== 'blue') return; const inCombat = updateCombat(unit, delta); if (!inCombat) recoverUnit(unit, delta); if (inCombat || !unit.route.length) return; const target = unit.route[unit.routeIndex]; if (!target) return; const distance = Math.hypot(target.x - unit.x, target.y - unit.y); const travel = unit.speed * delta; if (distance <= travel) { unit.x = target.x; unit.y = target.y; unit.routeIndex += 1; if (unit.routeIndex >= unit.route.length) { unit.route = []; unit.routeIndex = 0; } } else { unit.x += (target.x - unit.x) / distance * travel; unit.y += (target.y - unit.y) / distance * travel; } }
function drawUnit(unit) { if (unit.hp <= 0) return; const color = unit.side === 'blue' ? '#1911df' : '#f01818'; const outline = unit.side === 'blue' ? '#090b78' : '#76100e'; const opponent = findContact(unit); if (opponent) { ctx.strokeStyle = '#111'; ctx.lineWidth = 3; ctx.beginPath(); ctx.arc(unit.x, unit.y, unit.radius + 5 + Math.sin(Date.now() / 100) * 2, 0, Math.PI * 2); ctx.stroke(); } if (unit.selected) { ctx.strokeStyle = '#f9ed35'; ctx.lineWidth = 3; ctx.beginPath(); ctx.arc(unit.x, unit.y, unit.radius + 8, 0, Math.PI * 2); ctx.stroke(); } ctx.fillStyle = color; ctx.strokeStyle = outline; ctx.lineWidth = 2; ctx.beginPath(); ctx.arc(unit.x, unit.y, unit.radius, 0, Math.PI * 2); ctx.fill(); ctx.stroke(); ctx.fillStyle = '#0c201b'; ctx.fillRect(unit.x - 18, unit.y - unit.radius - 13, 36, 4); ctx.fillStyle = '#53e77e'; ctx.fillRect(unit.x - 18, unit.y - unit.radius - 13, 36 * unit.hp / 100, 4); ctx.fillStyle = '#0c201b'; ctx.fillRect(unit.x - 18, unit.y - unit.radius - 7, 36, 3); ctx.fillStyle = '#f2d42a'; ctx.fillRect(unit.x - 18, unit.y - unit.radius - 7, 36 * unit.morale / 100, 3); }
function render(now = performance.now()) { drawTerrain(); drawFog(); drawBases(); drawResource(); drawControlLine(); drawRoutes(); const delta = Math.min((now - lastFrame) / 1000, .05); lastFrame = now; if (!paused) allUnits().forEach(unit => moveUnit(unit, delta)); allUnits().filter(unit => unit.hp > 0 && (unit.side === 'blue' || units.some(blue => Math.hypot(blue.x - unit.x, blue.y - unit.y) < 145 || Math.hypot(116 - unit.x, 170 - unit.y) < 155))).forEach(drawUnit); if (dragging && dragStart && dragEnd) { ctx.fillStyle = 'rgba(0, 0, 0, .08)'; ctx.fillRect(dragStart.x, dragStart.y, dragEnd.x - dragStart.x, dragEnd.y - dragStart.y); ctx.strokeStyle = '#111'; ctx.lineWidth = 2; ctx.strokeRect(dragStart.x, dragStart.y, dragEnd.x - dragStart.x, dragEnd.y - dragStart.y); } requestAnimationFrame(render); }
function point(event) { const rect = canvas.getBoundingClientRect(); return { x: (event.clientX - rect.left) * canvas.width / rect.width, y: (event.clientY - rect.top) * canvas.height / rect.height }; }
canvas.addEventListener('pointerdown', event => { if (event.button !== 0) return; canvas.setPointerCapture(event.pointerId); const p = point(event); const hitUnit = units.find(unit => unit.hp > 0 && Math.hypot(unit.x - p.x, unit.y - p.y) < 25); if (hitUnit && hitUnit.selected) { routeDrawing = true; currentRoute = [{ x: hitUnit.x, y: hitUnit.y }]; return; } dragging = true; dragStart = p; dragEnd = p; });
canvas.addEventListener('pointermove', event => { const p = point(event); document.querySelector('#coords').textContent = `GRID ${Math.floor(p.x / 40).toString().padStart(2, '0')} : ${Math.floor(p.y / 40).toString().padStart(2, '0')}`; if (routeDrawing) { const last = currentRoute[currentRoute.length - 1]; if (Math.hypot(p.x - last.x, p.y - last.y) > 8) currentRoute.push(p); } else if (dragging) dragEnd = p; });
function finishPointer(event) { if (event.button !== 0 || (!dragging && !routeDrawing)) return; const p = point(event); if (routeDrawing) { if (Math.hypot(p.x - currentRoute[currentRoute.length - 1].x, p.y - currentRoute[currentRoute.length - 1].y) > 4) currentRoute.push(p); if (currentRoute.length > 1) selectedUnits().forEach((unit, index) => { const offset = index * 18; unit.route = currentRoute.map(point => ({ x: point.x + offset, y: point.y + offset })); unit.routeIndex = 1; unit.disengaging = true; }); routeDrawing = false; if (currentRoute.length > 1) showToast('蓝军轨迹已记录，单位将以有限速度前进。'); else { units.forEach(unit => unit.selected = Math.hypot(unit.x - p.x, unit.y - p.y) < 25); updateList(); updateReadout(); } return; } const box = { left: Math.min(dragStart.x, p.x), right: Math.max(dragStart.x, p.x), top: Math.min(dragStart.y, p.y), bottom: Math.max(dragStart.y, p.y) }; const isBox = Math.abs(p.x - dragStart.x) > 8 || Math.abs(p.y - dragStart.y) > 8; units.forEach(unit => unit.selected = unit.hp > 0 && (isBox ? unit.x > box.left && unit.x < box.right && unit.y > box.top && unit.y < box.bottom : Math.hypot(unit.x - p.x, unit.y - p.y) < 25)); dragging = false; updateList(); updateReadout(); }
canvas.addEventListener('pointerup', finishPointer);
document.addEventListener('pointerup', finishPointer);
canvas.addEventListener('contextmenu', event => { event.preventDefault(); showToast('请使用左键拖动，为蓝军绘制行军轨迹。'); });
document.querySelectorAll('.build-button').forEach(button => button.addEventListener('click', () => { const type = button.dataset.unit; const cost = type === 'armor' ? 160 : 80; const steel = Number(document.querySelector('#steel').textContent); if (steel < cost) { showToast('钢材不足，无法部署。'); return; } document.querySelector('#steel').textContent = steel - cost; const id = units.length + 1; units.push({ id, name: type === 'armor' ? `蓝军装甲师-${id}` : `蓝军步兵师-${id}`, type, side: 'blue', x: 240, y: 450, hp: 100, morale: 100, radius: type === 'armor' ? 15 : 11, speed: type === 'armor' ? 52 : 82, route: [], routeIndex: 0, selected: false }); document.querySelector('#queueText').textContent = '已部署'; updateList(); showToast('蓝军新单位已加入前线。'); }));
function togglePause() { paused = !paused; document.querySelector('#pauseButton').textContent = paused ? '▶' : 'Ⅱ'; showToast(paused ? '战场已暂停。' : '战场继续推进。'); }
document.querySelector('#pauseButton').addEventListener('click', togglePause); document.querySelector('#centerButton').addEventListener('click', () => { units.forEach(unit => unit.selected = false); updateList(); updateReadout(); showToast('视角已聚焦蓝军基地。'); }); document.querySelector('#soundButton').addEventListener('click', event => { event.currentTarget.classList.toggle('muted'); showToast(event.currentTarget.classList.contains('muted') ? '通讯静音。' : '通讯已恢复。'); });
document.addEventListener('keydown', event => { if (event.key === ' ') { event.preventDefault(); togglePause(); } if (event.key.toLowerCase() === 'q') document.querySelector('[data-unit="infantry"]').click(); if (event.key === 'Escape') { units.forEach(unit => unit.selected = false); updateList(); updateReadout(); } });
setInterval(() => { if (paused) return; seconds++; const minutes = Math.floor(seconds / 60).toString().padStart(2, '0'); const remainder = (seconds % 60).toString().padStart(2, '0'); document.querySelector('#timer').textContent = `${minutes}:${remainder}`; updateList(); }, 1000);
updateList(); updateReadout(); render();
